### ISSUE TITLE
Envoyfilter 0.5s timeout is not working

### ISSUE THREAD

**Issue by dharunt** [fluxninja/aperture#800] opened 2022-10-20 04:58 UTC
Hi

I have applied the isitoconfig chart from the helm repo, however the timeout 0.5s in ext_authz is not working. The graphs are not spiking up after generating traffic

I tried changing it to 5s initially , it looked like graph started spiking up , however after sometime, it stopped working.

Then I changed it to 10s and 20s , didn't work.

Can I know why 0.5s is set. I know that default value is 200ms. Is there any particular reason to set 0.5s as timeout ?

**Comment by hdkshingala** [comment] 2022-10-20 05:00
CC: @krdln @kwapik @tanveergill @harjotgill

**Comment by harjotgill** [comment] 2022-10-20 05:19
Hi @dharunt ! 
thanks for reporting this. Can you please share the screenshot from your grafana dashboard as it will give us a better idea as to what could be happening.

regarding the timeout, this can help understand why a larger timeout can help achieve fair scheduling — https://docs.fluxninja.com/docs/references/configuration/policy#v1-scheduler

**Comment by harjotgill** [comment] 2022-10-20 05:25
Also, since 0.6.0 release, the timeout has no impact on traffic getting detected or getting bypassed. If the traffic is not being tracked then it could be some other issue in the setup that we can help debug. 

See this change — https://github.com/fluxninja/aperture/commit/decf0e4a36e9af30d6f881ed9f775a42cbef3e35

**Comment by dharunt** [comment] 2022-10-20 07:08
<img width="1667" alt="Screenshot 2022-10-20 at 12 32 29 PM" src="https://user-images.githubusercontent.com/9652551/196879825-ae3df2a8-14ce-4189-afe4-27feccee508b.png">

**Comment by krdln** [comment] 2022-10-20 08:42
@dharunt Which release you're using?

**Comment by dharunt** [comment] 2022-10-20 08:43
0.6.1

**Comment by krdln** [comment] 2022-10-20 10:56
@dharunt Can you please also show the following metrics?
* "flowcontrol_requests_total"
* "flowcontrol_decisions_total"

**Comment by dharunt** [comment] 2022-10-20 12:59
@krdln I only have the sample dashboard with me.

Changing to 10s is not showing y axis in the graph (incoming_concurrency & accepted_concurrency) 
<img width="1666" alt="Screenshot 2022-10-20 at 6 24 22 PM" src="https://user-images.githubusercontent.com/9652551/196955191-cad4c548-71e9-48f5-8fe5-d349cc35723a.png">

**Comment by harjotgill** [comment] 2022-10-20 15:30
It’s a bit hard to figure out from the current info. Probably what could help -
1. description of the setup — app, traffic etc. what's the version of k8s and Istio?
2. Any errors seen in controller or agent logs?
3. Are services being discovered? Try this API on the agent - https://docs.fluxninja.com/docs/references/api/agent/entity-cache-service-get-entity-cache

**Comment by dharunt** [comment] 2022-10-21 04:04
@harjotgill Please find the details below:
1. App - just an api , Traffic - generating using k6s, k8s version - 1.17 , istio version - 1.14.4
2. Attached the controller log, agent log , I dont see any error.
3. I dont see the service (where istio sidecar is injected)
4. Flat line.

10s timeout is showing the data in the graph , however less than 10s is showing only the flat line.

We dont have authorization setup in our k8s cluster , May I know why ext_autz filter is used in the envoy filter ?
Service name : zosapi-nodeport

[entities.log](https://github.com/fluxninja/aperture/files/9835606/entities.log)
[controller.log](https://github.com/fluxninja/aperture/files/9835607/controller.log)

**Comment by hdkshingala** [comment] 2022-10-21 07:20
@dharunt Could you please do a test as below:

1. Use the EnvoyFilter with default timeout values.
2. Restart the api service pod which you want to monitor
3. Once the pod is up, get the IP of the pod using `kubectl get pod -o wide` in the namespace where the api service is running.
4. Check the agent running on the same node using the above command in the namespace where agent is deployed.
5. Run command: `k exec -it POD_ID -n NAMESPACE -- curl localhost:8080/v1/entities`
6. Wait for the IP of the api service pod to be listed in the response from the above command.
7. Once you can find the IP in the list, than start the load on the service and verify if it starts showing graphs in Grafana.

Thank you!

**Comment by dharunt** [comment] 2022-10-21 09:38
@hdkshingala 

I tried what you suggested.

The IP is listing in the agent where the service pod is running.

When I try to generate the traffic, i dont see any errors in controller and agent , the data is not showing in the graph.

**Comment by krdln** [comment] 2022-10-25 14:24
K8s version 1.17 is not supported (see https://docs.fluxninja.com/docs/get-started/installation/agent/supported-platforms).

We're relying on this feature https://kubernetes.io/docs/concepts/services-networking/service-traffic-policy, which is 1.23+. Without it, pod will communicate with random agent instead of the one on its node. I'm pretty convinced the behaviour you're observing (`flowcontrol_requests_total` on different nodes than expected) and fluxmeters working only _sometimes_ is caused by lack of this feature.

Perhaps you can try sidecar mode?

**Comment by harjotgill** [comment] 2022-10-26 19:51
I guess this issue can be closed as it's a platform compatibility issue. Sidecar mode is a better fit here as DaemonSet deployment requires Kubernetes 1.23+.

**Closed by harjotgill** 2022-10-26 19:51 UTC
Labels: Agent Envoy
